# Generated by Django 3.2.3 on 2021-05-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
